background {
	monitor = 
	path = ~/Pictures?wallpaper.jpg
	blur_passes = 2
	blur_size = 7
}

input-field {
	monitor = 
	size = 250, 60
	outline_thickness = 3
	dots_size = 0.25
	outer_color = rgba(0, 0, 0, 0)
	inner_color = rgba(0, 0, 0, 0.6)
	font_color = rgb(255, 255, 255)
	fade_on_empty = false
	placeholder_text = <i>Mot de passe...</i>
	position = 0, -100
	halign = center
	valign = center
}

label {
	monitor = 
	text = cmd[update:1000] echo "$(date +"%H:%M")"
	color = rgba(255, 255, 255, 0.8)
	font_size = 64
	position = 0, 150
	halign = center
	valign = center
}

